"""Shared support code for active document generation tools."""

from __future__ import annotations

import json as _json
import logging
import os
import re
import time
from typing import Any

import boto3
from botocore.config import Config as BotoConfig

from ..db_client import get_s3
from ..document_key_utils import is_allowed_document_key
from ..session_scope import extract_leaf_session_id, extract_tenant_id, extract_user_id
from ..template_registry import get_template_mapping

logger = logging.getLogger("eagle.document_generation")

# ── Bedrock client for LLM document generation ───────────────────────

_DOC_GEN_MODEL = os.getenv(
    "EAGLE_DOC_GEN_MODEL", "us.anthropic.claude-haiku-4-5-20251001-v1:0"
)
_AWS_REGION = os.getenv("AWS_REGION", "us-east-1")

_bedrock_doc_gen = None


def _get_doc_gen_bedrock():
    """Lazy-singleton Bedrock runtime client for document generation."""
    global _bedrock_doc_gen  # noqa: PLW0603
    if _bedrock_doc_gen is None:
        _bedrock_doc_gen = boto3.client(
            "bedrock-runtime",
            region_name=_AWS_REGION,
            config=BotoConfig(read_timeout=120, retries={"max_attempts": 2}),
        )
    return _bedrock_doc_gen


# ── Per-doc-type labels ──────────────────────────────────────────────

_DOC_TYPE_LABELS = {
    "sow": "Statement of Work",
    "igce": "Independent Government Cost Estimate",
    "market_research": "Market Research Report",
    "justification": "Justification & Approval",
    "acquisition_plan": "Acquisition Plan",
    "eval_criteria": "Evaluation Criteria",
    "security_checklist": "IT Security Checklist",
    "section_508": "Section 508 Compliance Statement",
    "cor_certification": "COR Certification",
    "contract_type_justification": "Contract Type Justification",
    "son_products": "Statement of Need — Products",
    "son_services": "Statement of Need — Services",
}

# ── System prompts for each doc type ─────────────────────────────────

_DOC_TYPE_SYSTEM_PROMPTS: dict[str, str] = {
    "sow": """You are an NCI federal acquisition document specialist. Generate a Statement of Work (SOW) in markdown format.

## Required Sections
1. BACKGROUND AND PURPOSE — Describe the agency need in 2-3 professional paragraphs
2. SCOPE — Define what the contractor shall provide, specific to the requirement
3. PERIOD OF PERFORMANCE — Base period + option years if applicable
4. APPLICABLE DOCUMENTS AND STANDARDS — FAR, HHSAR, and requirement-specific standards
5. TASKS AND REQUIREMENTS — Detailed task descriptions with measurable outcomes
6. DELIVERABLES — Specific deliverables with due dates/milestones
7. GOVERNMENT-FURNISHED PROPERTY — List items or state "None"
8. QUALITY ASSURANCE SURVEILLANCE PLAN — Performance standards and evaluation methods
9. PLACE OF PERFORMANCE — Specific location(s)
10. SECURITY REQUIREMENTS — Data sensitivity, clearance levels, compliance frameworks

## Rules
- Write professional federal acquisition language, not casual conversation
- Be specific to the requirement described in the context — do NOT use generic filler
- If information is missing for a section, write "[Contracting Officer to complete: <what's needed>]"
- Do NOT paste raw user messages or chat responses into the document
- Do NOT include appendices with conversation history
- Use markdown: H1 for doc type, H2 for sections, H3 for subsections, tables where appropriate
- Include "DRAFT — Generated {date}" in header metadata where {date} is today's date
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "igce": """You are an NCI federal acquisition cost estimator. Generate an Independent Government Cost Estimate (IGCE) in markdown format.

## Required Sections
1. PURPOSE — Why this estimate was prepared
2. METHODOLOGY — Basis for estimates (GSA pricing, historical data, market research, BLS data)
3. COST BREAKDOWN — Markdown table with Description, Qty, Unit Price, Total columns. If line items are provided, compute math exactly. If not, create reasonable line items based on the requirement.
4. ASSUMPTIONS AND LIMITATIONS — What the estimate is based on
5. CONFIDENCE LEVEL — Low/Medium/High with justification

## Math Rules
- All arithmetic must be exact — double-check totals
- Include subtotal, overhead %, contingency %, and grand total
- If overhead_rate or contingency_rate are provided, use those exact percentages
- Format currency with commas and 2 decimal places (e.g., $1,234.56)

## Rules
- Write professional federal cost estimation language
- Be specific to the requirement — do NOT use generic placeholders for cost items
- If cost data is missing, provide reasonable estimates based on the description and note them as estimates
- Do NOT paste raw user messages into the document
- Use markdown tables for cost breakdowns
- Include "DRAFT — For Budget Planning Purposes" in header
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "market_research": """You are an NCI federal acquisition market research analyst. Generate a Market Research Report in markdown format.

## Required Sections
1. DESCRIPTION OF NEED — What the government needs
2. SOURCES CONSULTED — SAM.gov, GSA Advantage, FPDS, industry publications, NIH contract history
3. POTENTIAL SOURCES — Known vendors with size status and contract vehicles
4. SMALL BUSINESS ANALYSIS — SBA size standards, set-aside potential
5. COMMERCIAL AVAILABILITY — Whether commercial solutions exist
6. RECOMMENDED ACQUISITION STRATEGY — Competition type, contract vehicle
7. RECOMMENDED CONTRACT VEHICLE — GSA MAS, NITAAC, full and open, set-aside

## Rules
- Write professional market research language per FAR Part 10
- If vendor data is provided, incorporate it. If not, note that web research is needed.
- Be specific to the NAICS code and requirement
- Do NOT paste raw user messages into the document
- Include NAICS code in the header if provided
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "justification": """You are an NCI federal acquisition specialist. Generate a Justification and Approval (J&A) for Other Than Full and Open Competition in markdown format.

## Required Sections
1. CONTRACTING ACTIVITY — NCI/NIH address
2. DESCRIPTION OF ACTION — What is being sole-sourced and to whom
3. DESCRIPTION OF SUPPLIES/SERVICES — Detailed requirement description
4. AUTHORITY CITED — FAR 6.302 authority (use provided authority or default to 6.302-1)
5. REASON FOR AUTHORITY — Detailed justification why only this source can meet the need
6. EFFORTS TO OBTAIN COMPETITION — Market research done, sources sought, etc.
7. DETERMINATION BY THE CONTRACTING OFFICER — Fair and reasonable price determination
8. ACTIONS TO REMOVE BARRIERS TO COMPETITION — Future plans for competitive acquisition
9. APPROVAL — Signature table with CO, Competition Advocate, and additional approvals per FAR 6.304

## Rules
- Write formal legal justification language per FAR Part 6
- The rationale must be substantive, not boilerplate — tie it to the specific requirement
- If information is missing, write "[Contracting Officer to complete: <what's needed>]"
- Do NOT paste raw user messages into the document
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "acquisition_plan": """You are an NCI federal acquisition planner. Generate an Acquisition Plan (AP) in streamlined format per FAR Part 7 in markdown.

## Required Sections
SECTION 1: ACQUISITION BACKGROUND AND OBJECTIVES
  1.1 Statement of Need
  1.2 Applicable Conditions (period of performance, estimated value, funding by FY)
  1.3 Cost — Basis for cost estimates
  1.4 Capability and Performance
  1.5 Delivery and Schedule
SECTION 2: PLAN OF ACTION
  2.1 Competitive Requirements — Competition strategy
  2.2 Source Selection — Evaluation approach
  2.3 Acquisition Considerations — Contract type, set-aside, FAR/HHSAR clauses
SECTION 3: MILESTONES — Table with target dates
SECTION 4: APPROVALS — Signature table

## Rules
- Write professional acquisition planning language per FAR Part 7
- Be specific about competition strategy, contract type, and set-aside decisions
- If funding_by_fy data is provided, use it in a table. Otherwise use placeholder FY rows.
- If information is missing, write "[Contracting Officer to complete: <what's needed>]"
- Do NOT paste raw user messages into the document
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "eval_criteria": """You are an NCI federal acquisition evaluation specialist. Generate Evaluation Criteria in markdown format per FAR Part 15.

## Required Sections
1. EVALUATION FACTORS — Listed in descending order of importance with weights
2. RATING SCALE — Table with ratings (Outstanding, Good, Acceptable, Marginal, Unacceptable) and descriptions
3. EVALUATION PROCESS — How TEP will evaluate, CPARS usage, price analysis
4. BASIS FOR AWARD — Best value determination statement

## Rules
- If evaluation factors are provided, use them. Otherwise create reasonable defaults for the requirement.
- Rating scale should follow standard FAR Part 15 conventions
- Write professional evaluation language
- If information is missing, write "[Contracting Officer to complete: <what's needed>]"
- Do NOT paste raw user messages into the document
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "security_checklist": """You are an NCI IT security specialist. Generate an IT Security Checklist in markdown format.

## Required Sections
1. SECURITY ASSESSMENT QUESTIONS — Table with 10 yes/no/N/A questions about IT access, PII, FISMA, clearances, cloud, FedRAMP, encryption
2. IMPACT LEVEL DETERMINATION — Low/Moderate/High with description table
3. REQUIRED FAR/HHSAR CLAUSES — Checklist of applicable security clauses (FAR 52.239-1, HHSAR 352.239-73, FAR 52.204-21, NIST 800-171)
4. IT SYSTEMS INVOLVED — List of systems
5. ISSM/ISSO REVIEW — Signature table

## Rules
- Pre-check answers based on provided context (e.g., if cloud_services is true, mark cloud question as Yes)
- Use the provided impact_level if given
- Write in security assessment language
- Do NOT paste raw user messages into the document
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "section_508": """You are an NCI Section 508 compliance specialist. Generate a Section 508 Compliance Statement in markdown format.

## Required Sections
1. APPLICABILITY DETERMINATION — Does this acquisition include EIT?
2. PRODUCT TYPE CHECKLIST — Software, Web, Telecom, Video, Self-Contained, Desktop, Electronic Docs
3. EXCEPTION DETERMINATION — National security, incidental, service personnel, micro-purchase, fundamental alteration, undue burden
4. VPAT/ACR STATUS — Vendor accessibility conformance report status
5. CONTRACT LANGUAGE — Checklist for SOW, eval criteria, contract clauses

## Rules
- Pre-check product types based on provided context
- Use the provided exception_claimed and vpat_status if given
- Write in accessibility compliance language
- Do NOT paste raw user messages into the document
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "cor_certification": """You are an NCI contracting specialist. Generate a Contracting Officer's Representative (COR) Certification document in markdown format.

## Required Sections
1. COR NOMINEE INFORMATION — Table with name, title, org, phone, email, FAC-COR level
2. FAC-COR CERTIFICATION — Table showing Level I/II/III requirements and which is applicable
3. DELEGATED DUTIES — Checklist of authorized COR duties (technical direction, invoice review, deliverable acceptance, performance monitoring, file maintenance, issue reporting)
4. LIMITATIONS — What the COR may NOT do (scope changes, cost authorization, period extension, contractual commitments)
5. SIGNATURES — Table with COR nominee, CO, supervisor

## Rules
- Use provided nominee information if available, otherwise use "[To be provided]" placeholders
- Use the provided FAC-COR level to pre-check the certification table
- Write in formal delegation language
- Do NOT paste raw user messages into the document
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "contract_type_justification": """You are an NCI federal acquisition specialist. Generate a Contract Type Justification (Determination and Findings) in markdown format.

## Required Sections
1. FINDINGS
  1.1 Description of Acquisition
  1.2 Contract Type Analysis — Table comparing FFP, T&M, CR, LH with risk to govt/contractor and recommendation
  1.3 Rationale for Contract Type Selection — Substantive justification
  1.4 Risk Assessment — Risk to government and contractor
  1.5 Requirements Definition — Why the selected type is appropriate

## Rules
- Pre-check the recommended contract type in the analysis table based on provided data
- The rationale must be substantive and tied to the specific requirement
- If information is missing, write "[Contracting Officer to complete: <what's needed>]"
- Do NOT paste raw user messages into the document
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "son_products": """You are an NCI federal acquisition specialist. Generate a Statement of Need (SON) for Products (including Equipment and Supplies) in markdown format.

## Required Sections
1. PROGRAM OFFICE / REQUESTING ORGANIZATION — Name, institute/center, division
2. DESCRIPTION OF NEED — Clear, non-restrictive description of what is needed and why
3. PRODUCT SPECIFICATIONS — Table with Item, Description, Quantity, Unit of Measure. Include salient characteristics, minimum requirements, and any brand-name-or-equal justifications per FAR 11.104.
4. INTENDED USE — How the products will be used in the program mission
5. DELIVERY REQUIREMENTS — Delivery location, timeline, any special handling
6. ESTIMATED COST — Budget estimate or price range with basis (GSA pricing, prior purchases, market research)
7. FUNDING INFORMATION — Appropriation, common accounting number if available, fiscal year
8. SPECIAL REQUIREMENTS — Installation, training, warranty, maintenance, IT security (FISMA), Section 508 compliance if applicable
9. MARKET RESEARCH SUMMARY — Sources consulted, small business availability, recommended acquisition strategy
10. APPROVALS — Signature table with Program Official, COR (if applicable), Branch Chief

## Rules
- Write professional federal acquisition language per FAR Part 11
- Product specifications must be non-restrictive unless a brand-name justification is provided
- If salient characteristics are provided, list them precisely. If not, write "[Program Office to provide salient characteristics]"
- If information is missing, write "[Contracting Officer to complete: <what's needed>]"
- Do NOT paste raw user messages into the document
- Include "DRAFT — Generated {date}" in header metadata where {date} is today's date
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",

    "son_services": """You are an NCI federal acquisition specialist. Generate a Statement of Need (SON) for Services based on Catalog Pricing in markdown format.

## Required Sections
1. PROGRAM OFFICE / REQUESTING ORGANIZATION — Name, institute/center, division
2. DESCRIPTION OF NEED — Clear description of the services needed and the program need driving the requirement
3. SERVICE REQUIREMENTS — Table with Service Category, Description, Estimated Hours/Quantity, Labor Category. Detail each service line item with expected outcomes.
4. PERIOD OF PERFORMANCE — Base period and option periods with start/end dates
5. PLACE OF PERFORMANCE — On-site, remote, or hybrid; specific location(s)
6. ESTIMATED COST — Budget estimate based on catalog pricing, GSA rates, or BLS data. Include a cost breakdown table if line items are available.
7. FUNDING INFORMATION — Appropriation, common accounting number if available, fiscal year
8. PERFORMANCE STANDARDS — Key deliverables, acceptance criteria, and quality metrics
9. SPECIAL REQUIREMENTS — Security clearances, IT access, certifications, Section 508, FISMA
10. MARKET RESEARCH SUMMARY — Sources consulted, contract vehicles considered, small business availability
11. APPROVALS — Signature table with Program Official, COR (if applicable), Branch Chief

## Rules
- Write professional federal acquisition language per FAR Part 11 and Part 37 (Service Contracting)
- Services must be described in terms of outcomes and deliverables, not specific personnel
- If catalog pricing is available, reference it. Otherwise estimate from GSA rates or BLS data.
- If information is missing, write "[Contracting Officer to complete: <what's needed>]"
- Do NOT paste raw user messages into the document
- Include "DRAFT — Generated {date}" in header metadata where {date} is today's date
- End with: *This document was generated by EAGLE — NCI Acquisition Assistant*""",
}


def _build_generation_prompt(doc_type: str, title: str, data: dict) -> str:
    """Build a structured prompt from session context data."""
    label = _DOC_TYPE_LABELS.get(doc_type, doc_type.replace("_", " ").title())
    parts = [f"Generate a {label} titled: {title}\n"]

    context_fields = {
        "description": "Requirement Description",
        "estimated_value": "Estimated Value",
        "period_of_performance": "Period of Performance",
        "security_requirements": "Security Requirements",
        "place_of_performance": "Place of Performance",
        "scope": "Scope Details",
        "deliverables": "Deliverables",
        "tasks": "Tasks",
        "competition": "Competition Strategy",
        "contract_type": "Contract Type",
        "set_aside": "Set-Aside",
        "naics_code": "NAICS Code",
        "authority": "Authority Cited",
        "contractor": "Contractor",
        "rationale": "Rationale",
        "evaluation_method": "Evaluation Method",
        "factors": "Evaluation Factors",
        "impact_level": "Impact Level",
        "cloud_services": "Cloud Services Involved",
        "nominee_name": "COR Nominee Name",
        "nominee_title": "COR Nominee Title",
        "nominee_org": "COR Nominee Organization",
        "nominee_email": "COR Nominee Email",
        "fac_cor_level": "FAC-COR Level",
        "contract_number": "Contract Number",
        "overhead_rate": "Overhead Rate (%)",
        "contingency_rate": "Contingency Rate (%)",
        "risk_to_government": "Risk to Government",
        "risk_to_contractor": "Risk to Contractor",
        "funding_by_fy": "Funding by Fiscal Year",
    }

    for key, label_text in context_fields.items():
        value = data.get(key)
        if value is None or value == "":
            continue
        if isinstance(value, list):
            if value and isinstance(value[0], dict):
                value = _json.dumps(value, default=str)
            else:
                value = "\n".join(f"- {item}" for item in value)
        elif isinstance(value, bool):
            value = "Yes" if value else "No"
        parts.append(f"**{label_text}:** {value}")

    # Add line items for IGCE
    line_items = data.get("line_items")
    if line_items:
        parts.append(f"**Line Items:** {_json.dumps(line_items, default=str)}")

    # Add conversation history as context (NOT to be pasted in)
    conv_history = data.get("conversation_history", [])
    if conv_history:
        parts.append(
            "\n## Conversation Context (for understanding the requirement only — do NOT paste into document)"
        )
        for msg in conv_history[-8:]:
            role = msg.get("role", "user").upper()
            text = str(msg.get("text", ""))[:500]
            parts.append(f"[{role}]: {text}")

    return "\n\n".join(parts)


def _minimal_skeleton(doc_type: str, title: str) -> str:
    """Honest fallback when Bedrock is unavailable."""
    label = _DOC_TYPE_LABELS.get(doc_type, doc_type.replace("_", " ").title())
    return f"""# {label.upper()}
## {title}
### National Cancer Institute (NCI)

**Document Status:** DRAFT — Generated {time.strftime("%Y-%m-%d %H:%M UTC")}

---

> **Note:** This document could not be generated because the AI service is temporarily
> unavailable. Please try again, or use the chat to request document generation
> (e.g., "Generate a {label} for this acquisition").

---
*This document was generated by EAGLE — NCI Acquisition Assistant*
"""


def _llm_generate_document(doc_type: str, title: str, data: dict) -> str:
    """Generate acquisition document content via Bedrock LLM call.

    Falls back to minimal skeleton if Bedrock is unavailable.
    """
    system_prompt = _DOC_TYPE_SYSTEM_PROMPTS.get(doc_type)
    if not system_prompt:
        logger.warning("No system prompt for doc_type=%s, using skeleton", doc_type)
        return _minimal_skeleton(doc_type, title)

    user_message = _build_generation_prompt(doc_type, title, data)

    try:
        bedrock = _get_doc_gen_bedrock()
        response = bedrock.converse(
            modelId=_DOC_GEN_MODEL,
            system=[{"text": system_prompt}],
            messages=[{"role": "user", "content": [{"text": user_message}]}],
            inferenceConfig={"maxTokens": 8192, "temperature": 0.3},
        )
        content = response["output"]["message"]["content"][0]["text"]
        return content.strip()
    except Exception as exc:
        logger.warning("Bedrock doc generation failed for %s: %s", doc_type, exc)
        return _minimal_skeleton(doc_type, title)


def _normalize_context_text(text: str) -> str:
    cleaned = (text or "").strip()
    if not cleaned:
        return ""
    marker = "[USER REQUEST]"
    if marker in cleaned:
        tail = cleaned.split(marker, 1)[1].strip()
        if "Instruction:" in tail:
            tail = tail.split("Instruction:", 1)[0].strip()
        if tail:
            cleaned = tail
    return cleaned


def _load_recent_user_context(session_id: str | None = None) -> list[str]:
    leaf_session_id = extract_leaf_session_id(session_id)
    if not leaf_session_id:
        return []

    tenant_id = extract_tenant_id(session_id)
    user_id = extract_user_id(session_id)

    try:
        from ..session_store import get_messages

        messages = get_messages(leaf_session_id, tenant_id, user_id, limit=30)
        context_texts: list[str] = []
        for msg in messages:
            role = msg.get("role", "")
            if role not in ("user", "assistant"):
                continue

            content = msg.get("content", "")
            text = ""
            if isinstance(content, str):
                text = _normalize_context_text(content)
            elif isinstance(content, list):
                text_parts: list[str] = []
                for block in content:
                    if isinstance(block, dict):
                        block_text = block.get("text")
                        if isinstance(block_text, str) and block_text.strip():
                            text_parts.append(block_text.strip())
                if text_parts:
                    text = _normalize_context_text("\n".join(text_parts))

            if text:
                prefix = "" if role == "user" else "[ASSISTANT] "
                context_texts.append(prefix + text)

        return context_texts[-12:]
    except Exception as exc:
        logger.debug("Could not load session context for create_document: %s", exc)
        return []


def _extract_first_money_value(text: str) -> str | None:
    if not text:
        return None

    match = re.search(r"\$[0-9][0-9,]*(?:\.[0-9]+)?", text)
    if match:
        return match.group(0)

    match = re.search(
        r"\b[0-9][0-9,]*(?:\.[0-9]+)?\s*(?:million|billion|k|m)\b",
        text,
        flags=re.IGNORECASE,
    )
    if match:
        return match.group(0)
    return None


def _extract_period(text: str) -> str | None:
    if not text:
        return None
    match = re.search(
        r"\b\d+\s*(?:month|months|year|years)\b(?:[^.,;\n]{0,40})",
        text,
        flags=re.IGNORECASE,
    )
    if match:
        return match.group(0).strip()
    return None


_GENERATION_TRIGGER_RE = re.compile(
    r"^(generate|create|draft|write|produce|prepare|build|make)\s+"
    r"(the|a|an|my|our)?\s*"
    r"(statement of work|sow|igce|ige|cost estimate|market research|"
    r"acquisition plan|justification|document|report)",
    re.IGNORECASE,
)


def _is_generation_trigger(text: str) -> bool:
    t = text.strip()
    if len(t) > 200:
        return False
    return bool(_GENERATION_TRIGGER_RE.search(t))


def _extract_section_bullets(text: str) -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    current: str | None = None
    aliases = {
        "project description": "project_description",
        "technical requirements": "technical_requirements",
        "scope of work": "scope_of_work",
        "deliverables": "deliverables",
        "environment tiers": "environment_tiers",
        "security": "security",
    }

    for raw_line in (text or "").splitlines():
        line = raw_line.strip()
        if not line:
            continue

        heading_key = line.rstrip(":").strip().lower()
        if heading_key in aliases:
            current = aliases[heading_key]
            sections.setdefault(current, [])
            continue

        if line.startswith("- ") or line.startswith("* "):
            item = line[2:].strip().strip('"')
            if item:
                sections.setdefault(current or "general", []).append(item)

    return sections


def _augment_document_data_from_context(
    doc_type: str,
    title: str,
    data: dict | None,
    session_id: str | None,
) -> dict:
    merged = dict(data or {})
    context_messages = _load_recent_user_context(session_id)
    if not context_messages:
        return merged

    user_msgs = [m for m in context_messages if not m.startswith("[ASSISTANT] ")]
    assistant_msgs = [
        m.removeprefix("[ASSISTANT] ")
        for m in context_messages
        if m.startswith("[ASSISTANT] ")
    ]
    substantive_user_msgs = [m for m in user_msgs if not _is_generation_trigger(m)]
    last_user_text = (substantive_user_msgs or user_msgs)[-1] if user_msgs else ""
    context_blob = " ".join(context_messages[-8:])

    requirement = (last_user_text or context_blob).strip()
    if requirement:
        requirement = requirement[:500]

    money = _extract_first_money_value(context_blob)
    period = _extract_period(context_blob)

    if requirement:
        merged.setdefault("description", requirement)
        merged.setdefault("requirement", requirement)
        merged.setdefault("objective", requirement)
    if money:
        merged.setdefault("estimated_cost", money)
        merged.setdefault("estimated_value", money)
        merged.setdefault("budget", money)
        merged.setdefault("total_estimate", money)
    if period:
        merged.setdefault("period_of_performance", period)
        merged.setdefault("timeline", period)

    parsed_sections = _extract_section_bullets("\n".join(context_messages[-3:]))
    project_description = " ".join(
        parsed_sections.get("project_description", [])
    ).strip()
    if project_description:
        existing_desc = str(merged.get("description", "")).strip()
        if (
            not existing_desc
            or "project description" in existing_desc.lower()
            or len(existing_desc) > 320
        ):
            merged["description"] = project_description[:500]
        merged.setdefault("requirement", project_description[:500])
        merged.setdefault("objective", project_description[:500])
    if parsed_sections.get("deliverables"):
        merged.setdefault("deliverables", parsed_sections["deliverables"][:15])
    if parsed_sections.get("security"):
        merged.setdefault(
            "security_requirements", "; ".join(parsed_sections["security"])[:600]
        )
    if parsed_sections.get("environment_tiers"):
        merged.setdefault(
            "place_of_performance",
            "; ".join(parsed_sections["environment_tiers"])[:300],
        )

    if doc_type == "igce":
        merged.setdefault("item_name", title or "Primary acquisition item")
    if doc_type == "market_research":
        merged.setdefault("requirement_summary", requirement or title)
    if doc_type == "sow":
        scope_items = parsed_sections.get("scope_of_work", [])
        tech_items = parsed_sections.get("technical_requirements", [])
        combined_tasks = (scope_items + tech_items)[:20]
        if combined_tasks:
            merged.setdefault("tasks", combined_tasks)
        if scope_items:
            merged.setdefault(
                "scope", "\n".join(f"- {item}" for item in scope_items[:10])
            )
        elif substantive_user_msgs:
            merged.setdefault("scope", max(substantive_user_msgs[-6:], key=len)[:500])

    if assistant_msgs:
        clean_assistant = [
            msg
            for msg in assistant_msgs
            if not re.search(
                r"Your task is to create a detailed summary|"
                r"You are an? .{0,30}(?:assistant|agent|specialist)|"
                r"SYSTEM PROMPT|"
                r"<instructions>",
                msg[:200],
                re.IGNORECASE,
            )
        ]
        source = clean_assistant or assistant_msgs
        merged.setdefault("conversation_context", max(source[-4:], key=len)[:3000])

    all_msgs = []
    for message in context_messages:
        if message.startswith("[ASSISTANT] "):
            all_msgs.append({"role": "assistant", "text": message[12:]})
        else:
            all_msgs.append({"role": "user", "text": message})
    if all_msgs:
        merged.setdefault("conversation_history", all_msgs)

    return merged


# DEPRECATED: Use ai_document_schema.DOC_TYPE_ALIASES instead.
# This alias map is kept for backward compatibility with tests.
# The canonical source of truth is now server/app/ai_document_schema.py
# Phase 1 of Canonical Schema Propagation (2026-04-09)
_DOC_TYPE_ALIASES = {
    "ige": "igce",
    "igce": "igce",
    "independent_government_estimate": "igce",
    "independent_government_cost_estimate": "igce",
    "cost_estimate": "igce",
    "statement_of_work": "sow",
    # RFP sections → closest existing types
    "section_l": "eval_criteria",
    "instructions_to_offerors": "eval_criteria",
    "section_m": "eval_criteria",
    "evaluation_factors": "eval_criteria",
    "evaluation_criteria": "eval_criteria",
    "source_selection_plan": "acquisition_plan",
    "ssp": "acquisition_plan",
}

_TITLE_DOC_TYPE_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\b(statement\s+of\s+work|sow)\b", re.IGNORECASE), "sow"),
    (
        re.compile(
            r"\b(igce|ige|independent\s+government\s+(?:cost\s+)?estimate|cost\s+estimate)\b",
            re.IGNORECASE,
        ),
        "igce",
    ),
    (re.compile(r"\bmarket\s+research\b", re.IGNORECASE), "market_research"),
    (re.compile(r"\bacquisition\s+plan\b", re.IGNORECASE), "acquisition_plan"),
    (
        re.compile(
            r"\b(j\s*(?:&|and)\s*a|justification(?:\s*&\s*approval)?|sole\s+source)\b",
            re.IGNORECASE,
        ),
        "justification",
    ),
    # RFP sections
    (re.compile(r"\bsection\s+[lLmM]\b", re.IGNORECASE), "eval_criteria"),
    (re.compile(r"\binstructions?\s+to\s+offerors?\b", re.IGNORECASE), "eval_criteria"),
    (re.compile(r"\bsource\s+selection\s+plan\b", re.IGNORECASE), "acquisition_plan"),
]


def _infer_doc_type_from_title(title: str) -> str | None:
    if not title:
        return None
    for pattern, doc_type in _TITLE_DOC_TYPE_PATTERNS:
        if pattern.search(title):
            return doc_type
    return None


def _normalize_create_document_doc_type(raw_doc_type: Any, title: str) -> str:
    """DEPRECATED: Use ai_document_schema.normalize_doc_type() instead.

    This function is kept for backward compatibility with existing tests.
    The canonical source of truth is now server/app/ai_document_schema.py
    Phase 2 of Canonical Schema Propagation (2026-04-09)
    """
    # Delegate to canonical schema for normalization
    from app.ai_document_schema import normalize_doc_type

    normalized = normalize_doc_type(str(raw_doc_type or ""))
    inferred = _infer_doc_type_from_title(title)

    if normalized == "sow" and inferred == "igce":
        logger.info(
            "Overriding create_document doc_type from sow to igce based on title=%r",
            title,
        )
        return inferred
    if normalized:
        return normalized
    if inferred:
        return inferred
    return "sow"


def _default_output_format_for_doc_type(doc_type: str) -> str:
    mapping = get_template_mapping(doc_type)
    if mapping:
        return mapping.file_type
    return "md"


def _looks_like_unfilled_template_preview(doc_type: str, preview: str) -> bool:
    if not preview:
        return False
    try:
        from ..template_registry import validate_document_completeness

        report = validate_document_completeness(doc_type, preview)
        if report is not None:
            return report.completeness_pct < 30.0
    except ImportError:
        pass

    if re.search(r"\{\{[A-Z_]{3,}\}\}", preview):
        return True

    markers = {
        "sow": [
            "this section should provide brief description of the project",
            "the background information should identify the requirement in very general terms",
            "sample language",
            "table of contents",
        ],
        "acquisition_plan": [
            "this section should describe the requirement",
            "describe the competition strategy",
            "[tbd]",
            "revised july 2024",
            "far 7.1",
        ],
        "market_research": [
            "[analysis of small business availability",
            "[analysis of whether commercial",
            "this section should describe the market",
            "[insert requirement description",
        ],
        "justification": [
            "[contractor name]",
            "[provide detailed rationale",
            "[describe efforts to compete",
            "[insert authority",
        ],
        "cor_certification": [
            "[nominee name]",
            "[nominee title]",
            "[contract number]",
        ],
    }.get(doc_type, [])
    return (
        sum(
            1
            for marker in markers
            if marker.lower() in " ".join(preview.lower().split())
        )
        >= 2
    )


_SOW_SECTION_HINTS: dict[str, str] = {
    "1": "background and purpose",
    "2": "scope",
    "3": "period of performance",
    "4": "applicable documents and standards",
    "5": "tasks and requirements",
    "6": "deliverables",
    "7": "government-furnished property",
    "8": "quality assurance surveillance plan",
    "9": "place of performance",
    "10": "security requirements",
}


def _extract_sow_clear_targets(edit_request: str) -> list[str]:
    req = (edit_request or "").strip().lower()
    if not req:
        return []
    clear_intent = (
        "clear" in req or "blank" in req or "to be completed" in req or "remove" in req
    )
    if not clear_intent:
        return []

    targets: list[str] = []
    for section_num in re.findall(r"\bsection\s*(\d{1,2})\b", req):
        hint = _SOW_SECTION_HINTS.get(section_num)
        if hint and hint not in targets:
            targets.append(hint)

    for alias in (
        "background and purpose",
        "scope",
        "period of performance",
        "applicable documents and standards",
        "tasks and requirements",
        "deliverables",
        "government-furnished property",
        "quality assurance surveillance plan",
        "place of performance",
        "security requirements",
    ):
        if alias in req and alias not in targets:
            targets.append(alias)

    if "scope" in req and "scope" not in targets:
        targets.append("scope")
    return targets


def _apply_sow_clear_edits(current_content: str, edit_request: str) -> str | None:
    if not isinstance(current_content, str) or not current_content.strip():
        return None

    targets = _extract_sow_clear_targets(edit_request)
    if not targets:
        return None

    heading_matches = list(re.finditer(r"(?m)^##\s+(.+?)\s*$", current_content))
    if not heading_matches:
        return None

    rebuilt: list[str] = []
    cursor = 0
    changed = False

    for idx, heading_match in enumerate(heading_matches):
        heading_end = heading_match.end()
        next_start = (
            heading_matches[idx + 1].start()
            if idx + 1 < len(heading_matches)
            else len(current_content)
        )
        heading_text = heading_match.group(1).strip().lower()
        body_text = current_content[heading_end:next_start]
        rebuilt.append(current_content[cursor:heading_end])

        if any(target in heading_text for target in targets):
            if body_text.strip() != "[To be completed]":
                changed = True
            rebuilt.append("\n\n[To be completed]\n\n")
        else:
            rebuilt.append(body_text)
        cursor = next_start

    updated = "".join(rebuilt)
    return updated if changed else None


def _update_document_content(
    tenant_id: str,
    doc_key: str,
    content: str,
    change_source: str = "ai_edit",
    session_id: str | None = None,
) -> dict:
    if not doc_key:
        return {"error": "update_existing_key is required but empty"}
    if not content:
        return {
            "error": "content is required for update. Provide the full document markdown in the content parameter."
        }

    user_id = extract_user_id(session_id)
    bucket = os.getenv("S3_BUCKET", "eagle-documents-695681773636-dev")

    if not is_allowed_document_key(doc_key, tenant_id, user_id):
        return {"error": "Access denied: document key is not within an allowed scope"}

    if "/packages/" in doc_key:
        from ..document_service import create_package_document_version

        parts = doc_key.split("/")
        try:
            pkg_idx = parts.index("packages")
            package_id = parts[pkg_idx + 1]
            filename = parts[-1]
            doc_type = (
                filename.split("_v")[0]
                if "_v" in filename
                else filename.rsplit(".", 1)[0]
            )
            title = doc_type.replace("_", " ").title()
        except (ValueError, IndexError):
            return {"error": "Invalid package document key format"}

        result = create_package_document_version(
            tenant_id=tenant_id,
            package_id=package_id,
            doc_type=doc_type,
            content=content,
            title=title,
            file_type="md",
            created_by_user_id=user_id,
            session_id=session_id,
            change_source=change_source,
        )
        if not result.success:
            return {"error": result.error or "Failed to create document version"}
        return {
            "success": True,
            "mode": "update_package",
            "package_id": package_id,
            "doc_type": doc_type,
            "document_type": doc_type,
            "title": title,
            "s3_key": result.s3_key,
            "key": result.s3_key,
            "version": result.version,
            "document_id": result.document_id,
            "status": "draft",
            "content": content,
            "word_count": len(content.split()),
            "message": f"Document updated (version {result.version})",
        }

    try:
        s3 = get_s3()
        s3.put_object(
            Bucket=bucket,
            Key=doc_key,
            Body=content.encode("utf-8"),
            ContentType="text/markdown; charset=utf-8",
        )
        from ..changelog_store import write_document_changelog_entry

        write_document_changelog_entry(
            tenant_id=tenant_id,
            document_key=doc_key,
            change_type="update",
            change_source=change_source,
            change_summary="Updated document content",
            actor_user_id=user_id,
            session_id=session_id,
        )
        # Extract doc_type from key filename (e.g., "sow_20260325.md" → "sow")
        ws_filename = doc_key.rsplit("/", 1)[-1] if "/" in doc_key else doc_key
        ws_doc_type = ws_filename.split("_", 1)[0] if "_" in ws_filename else ws_filename.rsplit(".", 1)[0]
        return {
            "success": True,
            "mode": "update_workspace",
            "s3_key": doc_key,
            "key": doc_key,
            "doc_type": ws_doc_type,
            "document_type": ws_doc_type,
            "title": ws_doc_type.replace("_", " ").title(),
            "content": content,
            "word_count": len(content.split()),
            "message": "Document updated",
        }
    except Exception as exc:
        logger.warning("Failed to update workspace document %s: %s", doc_key, exc)
        return {"error": f"Failed to update document: {exc}"}


# ── Provenance metadata injection ────────────────────────────────────

_EAGLE_FOOTER_RE = re.compile(
    r"\n---\s*\n\s*\*{1,2}This document was generated by EAGLE[^*]*\*{1,2}\s*(?:\n---\s*)?$"
)


def _append_provenance_metadata(
    content: str,
    provenance: dict | None,
    source: str,
    generated_at: str,
) -> str:
    """Append a Document Metadata section to generated content, replacing the bare footer."""
    if "## Document Metadata" in content:
        return content  # double-injection guard

    # Strip old bare footer if present
    content = _EAGLE_FOOTER_RE.sub("", content)

    # Build metadata table rows
    rows = [
        ("Generated by", "EAGLE — NCI Acquisition Assistant"),
    ]
    if provenance:
        rows.append(("Template", provenance.get("template_id", "N/A")))
        rows.append(("Template Source", provenance.get("template_source", source)))
        rows.append(("Template Version", f"v{provenance.get('template_version', 1)}"))
    else:
        rows.append(("Template", "Built-in markdown generator"))
        rows.append(("Template Source", source or "markdown_fallback"))
    rows.append(
        ("Document Type", provenance.get("doc_type", "N/A") if provenance else "N/A")
    )
    rows.append(("Generated", generated_at))

    table_lines = ["| Field | Value |", "|-------|-------|"]
    for field, value in rows:
        table_lines.append(f"| **{field}** | {value} |")

    metadata_section = "\n".join(
        [
            "",
            "---",
            "",
            "## Document Metadata",
            "",
            *table_lines,
            "",
            "*This is a draft document. Review and customize before official use.*",
        ]
    )

    return content.rstrip() + "\n" + metadata_section + "\n"


def _generate_sow(title: str, data: dict) -> str:
    return _llm_generate_document("sow", title, data)


def _generate_igce(title: str, data: dict) -> str:
    return _llm_generate_document("igce", title, data)


def _generate_market_research(title: str, data: dict) -> str:
    return _llm_generate_document("market_research", title, data)


def _generate_justification(title: str, data: dict) -> str:
    return _llm_generate_document("justification", title, data)


def _generate_acquisition_plan(title: str, data: dict) -> str:
    return _llm_generate_document("acquisition_plan", title, data)


def _generate_eval_criteria(title: str, data: dict) -> str:
    return _llm_generate_document("eval_criteria", title, data)


def _generate_security_checklist(title: str, data: dict) -> str:
    return _llm_generate_document("security_checklist", title, data)


def _generate_section_508(title: str, data: dict) -> str:
    return _llm_generate_document("section_508", title, data)


def _generate_cor_certification(title: str, data: dict) -> str:
    return _llm_generate_document("cor_certification", title, data)


def _generate_contract_type_justification(title: str, data: dict) -> str:
    return _llm_generate_document("contract_type_justification", title, data)


def _generate_son_products(title: str, data: dict) -> str:
    return _llm_generate_document("son_products", title, data)


def _generate_son_services(title: str, data: dict) -> str:
    return _llm_generate_document("son_services", title, data)
