"""Document Store -- DynamoDB-backed DOCUMENT# entity CRUD with version tracking.

Phase 3 Step 15. Stores acquisition documents (SOW, IGCE, etc.) generated by
EAGLE agents. Supports versioning with automatic supersession of prior versions.

Entity format:
    PK:  DOCUMENT#{tenant_id}
    SK:  DOCUMENT#{package_id}#{doc_type}#{version}

GSI (GSI1):
    GSI1PK:  TENANT#{tenant_id}
    GSI1SK:  DOCUMENT#{package_id}#{doc_type}#{version:04d}
"""
import uuid
import logging
from datetime import datetime
from typing import Optional

from botocore.exceptions import BotoCoreError, ClientError
from boto3.dynamodb.conditions import Attr, Key

from .db_client import get_table, item_to_dict

logger = logging.getLogger('eagle.document_store')


# -- Helpers ---------------------------------------------------------------


def _sk(package_id: str, doc_type: str, version: int) -> str:
    return f'DOCUMENT#{package_id}#{doc_type}#{version}'


def _gsi1_sk(package_id: str, doc_type: str, version: int) -> str:
    return f'DOCUMENT#{package_id}#{doc_type}#{version:04d}'


# -- Core CRUD -------------------------------------------------------------

def create_document(
    tenant_id: str,
    package_id: str,
    doc_type: str,
    content: str,
    generated_by: str,
    session_id: Optional[str] = None,
    template_id: Optional[str] = None,
    template_provenance: Optional[dict] = None,
    system_tags: Optional[list] = None,
    user_tags: Optional[list] = None,
    far_tags: Optional[list] = None,
    completeness_pct: Optional[float] = None,
) -> dict:
    """Create a new versioned document, superseding all previous versions.

    Scans existing docs for this package + doc_type, takes the highest version
    found, writes new doc at version N+1 (or v1 if none exist), then marks all
    prior versions as superseded.

    Args:
        template_provenance: Structured provenance dict with keys:
            template_id, template_source, template_version, template_name, doc_type
        system_tags:  Auto-derived tags (e.g. ["phase:planning", "threshold:sat"])
        user_tags:    Free-form user labels (e.g. ["priority", "needs-review"])
        far_tags:     FAR clause references (e.g. ["FAR 52.219-8", "FAR 6.302"])
        completeness_pct: 0-100 completeness percentage from template schema validation

    Returns the newly created document dict.
    """
    table = get_table()
    now = datetime.utcnow().isoformat()

    existing = get_document_history(tenant_id, package_id, doc_type)
    next_version = (max(d['version'] for d in existing) + 1) if existing else 1

    document_id = str(uuid.uuid4())

    item: dict = {
        'PK': f'DOCUMENT#{tenant_id}',
        'SK': _sk(package_id, doc_type, next_version),
        'GSI1PK': f'TENANT#{tenant_id}',
        'GSI1SK': _gsi1_sk(package_id, doc_type, next_version),
        'document_id': document_id,
        'package_id': package_id,
        'doc_type': doc_type,
        'content': content,
        'version': next_version,
        'status': 'draft',
        'generated_by': generated_by,
        'created_at': now,
    }
    if session_id is not None:
        item['session_id'] = session_id
    if template_id is not None:
        item['template_id'] = template_id
    if template_provenance is not None:
        item['template_provenance'] = template_provenance
    if system_tags:
        item['system_tags'] = system_tags
    if user_tags:
        item['user_tags'] = user_tags
    if far_tags:
        item['far_tags'] = far_tags
    if completeness_pct is not None:
        item['completeness_pct'] = completeness_pct

    try:
        table.put_item(Item=item)
        logger.debug(
            'document_store.create_document: [%s/%s/%s] v%s created',
            tenant_id, package_id, doc_type, next_version,
        )
    except (ClientError, BotoCoreError) as e:
        logger.error('document_store.create_document failed: %s', e)
        raise

    for prior in existing:
        if prior['status'] != 'superseded':
            try:
                table.update_item(
                    Key={
                        'PK': f'DOCUMENT#{tenant_id}',
                        'SK': _sk(package_id, doc_type, prior['version']),
                    },
                    UpdateExpression='SET #s = :superseded',
                    ExpressionAttributeNames={'#s': 'status'},
                    ExpressionAttributeValues={':superseded': 'superseded'},
                )
            except (ClientError, BotoCoreError) as e:
                logger.warning(
                    'document_store.create_document: failed to supersede v%s: %s',
                    prior['version'], e,
                )

    return item


def get_document(
    tenant_id: str,
    package_id: str,
    doc_type: str,
    version: Optional[int] = None,
) -> Optional[dict]:
    """Fetch a document by tenant, package, doc_type, and optional version.

    If version is None, returns the latest (highest version number).
    Returns None if not found.
    """
    if version is not None:
        try:
            table = get_table()
            response = table.get_item(
                Key={
                    'PK': f'DOCUMENT#{tenant_id}',
                    'SK': _sk(package_id, doc_type, version),
                }
            )
            raw = response.get('Item')
            return item_to_dict(raw) if raw else None
        except (ClientError, BotoCoreError) as e:
            logger.error('document_store.get_document failed: %s', e)
            return None

    history = get_document_history(tenant_id, package_id, doc_type)
    if not history:
        return None
    return max(history, key=lambda d: d['version'])


def finalize_document(
    tenant_id: str,
    package_id: str,
    doc_type: str,
    version: int,
) -> Optional[dict]:
    """Transition a document from draft to final status.

    Returns the updated document dict, or None if the document was not found.
    """
    table = get_table()
    pk = f'DOCUMENT#{tenant_id}'
    sk = _sk(package_id, doc_type, version)

    try:
        response = table.update_item(
            Key={'PK': pk, 'SK': sk},
            UpdateExpression='SET #s = :final',
            ConditionExpression='attribute_exists(PK)',
            ExpressionAttributeNames={'#s': 'status'},
            ExpressionAttributeValues={':final': 'final'},
            ReturnValues='ALL_NEW',
        )
        attrs = response.get('Attributes', {})
        return item_to_dict(attrs) if attrs else None
    except ClientError as e:
        if e.response['Error']['Code'] == 'ConditionalCheckFailedException':
            logger.warning(
                'document_store.finalize_document: item not found [%s/%s/%s v%s]',
                tenant_id, package_id, doc_type, version,
            )
            return None
        logger.error('document_store.finalize_document failed: %s', e)
        return None
    except BotoCoreError as e:
        logger.error('document_store.finalize_document failed: %s', e)
        return None


def list_package_documents(tenant_id: str, package_id: str) -> list[dict]:
    """Return the latest version of each doc_type for a given package.

    Queries all DOCUMENT# items whose SK begins with DOCUMENT#{package_id}#,
    then selects the highest version per doc_type.
    """
    table = get_table()
    sk_prefix = f'DOCUMENT#{package_id}#'

    try:
        response = table.query(
            KeyConditionExpression=(
                Key('PK').eq(f'DOCUMENT#{tenant_id}')
                & Key('SK').begins_with(sk_prefix)
            ),
        )
        items = [item_to_dict(i) for i in response.get('Items', [])]
    except (ClientError, BotoCoreError) as e:
        logger.error('document_store.list_package_documents failed: %s', e)
        return []

    latest: dict[str, dict] = {}
    for item in items:
        dt = item.get('doc_type', '')
        if dt not in latest or item['version'] > latest[dt]['version']:
            latest[dt] = item

    return sorted(latest.values(), key=lambda d: d.get('doc_type', ''))


def get_document_history(
    tenant_id: str,
    package_id: str,
    doc_type: str,
) -> list[dict]:
    """Return all versions of a given doc_type within a package, sorted ascending."""
    table = get_table()
    sk_prefix = f'DOCUMENT#{package_id}#{doc_type}#'

    try:
        response = table.query(
            KeyConditionExpression=(
                Key('PK').eq(f'DOCUMENT#{tenant_id}')
                & Key('SK').begins_with(sk_prefix)
            ),
        )
        items = [item_to_dict(i) for i in response.get('Items', [])]
        return sorted(items, key=lambda d: d.get('version', 0))
    except (ClientError, BotoCoreError) as e:
        logger.error('document_store.get_document_history failed: %s', e)
        return []


def get_document_by_id(
    tenant_id: str,
    document_id: str,
) -> Optional[dict]:
    """Fetch a document by tenant and document_id.

    The current table schema does not index document_id directly, so this uses
    the tenant partition with a filter expression as an MVP lookup path.
    """
    table = get_table()

    try:
        response = table.query(
            KeyConditionExpression=Key("PK").eq(f"DOCUMENT#{tenant_id}"),
            FilterExpression=Attr("document_id").eq(document_id),
            Limit=1,
        )
        items = response.get("Items", [])
        if not items:
            return None
        return item_to_dict(items[0])
    except (ClientError, BotoCoreError) as e:
        logger.error("document_store.get_document_by_id failed: %s", e)
        return None


def create_document_from_s3(
    tenant_id: str,
    package_id: str,
    doc_type: str,
    filename: str,
    file_type: str,
    content: bytes,
    source_s3_key: str,
    created_by: str,
) -> dict:
    """Create a document entry from an S3 template copy.

    Stores binary content in S3 and creates a DynamoDB reference entry.
    Used when copying templates from the S3 library into acquisition packages.

    Args:
        tenant_id: Tenant ID
        package_id: Target package ID
        doc_type: Document type (sow, igce, etc.)
        filename: Original filename
        file_type: File extension (docx, xlsx, etc.)
        content: Binary file content
        source_s3_key: Original S3 key the template was copied from
        created_by: User ID who initiated the copy

    Returns:
        Created document dict with document_id
    """
    import base64

    table = get_table()
    now = datetime.utcnow().isoformat()

    existing = get_document_history(tenant_id, package_id, doc_type)
    next_version = (max(d['version'] for d in existing) + 1) if existing else 1

    document_id = str(uuid.uuid4())

    # Store binary content as base64 for DynamoDB (MVP approach)
    # Production would upload to S3 and store a reference
    content_b64 = base64.b64encode(content).decode('utf-8') if content else None

    # Size guard: DynamoDB has a 400KB item limit. If content is too large,
    # keep it in S3 and store just the reference.
    if content_b64 and len(content_b64) > 350_000:
        logger.info(
            'document_store.create_document_from_s3: content too large for DynamoDB (%d bytes), storing S3 reference only',
            len(content_b64),
        )
        content_b64 = None  # Will use source_s3_key as reference

    item: dict = {
        'PK': f'DOCUMENT#{tenant_id}',
        'SK': _sk(package_id, doc_type, next_version),
        'GSI1PK': f'TENANT#{tenant_id}',
        'GSI1SK': _gsi1_sk(package_id, doc_type, next_version),
        'document_id': document_id,
        'package_id': package_id,
        'doc_type': doc_type,
        'filename': filename,
        'file_type': file_type,
        'content_b64': content_b64,
        'source_s3_key': source_s3_key,
        'version': next_version,
        'status': 'draft',
        'generated_by': created_by,
        'created_at': now,
        'source_type': 's3_template',
    }

    try:
        table.put_item(Item=item)
        logger.info(
            'document_store.create_document_from_s3: [%s/%s/%s] v%s created from %s',
            tenant_id, package_id, doc_type, next_version, source_s3_key,
        )
    except (ClientError, BotoCoreError) as e:
        logger.error('document_store.create_document_from_s3 failed: %s', e)
        raise

    # Supersede prior versions
    for prior in existing:
        if prior['status'] != 'superseded':
            try:
                table.update_item(
                    Key={
                        'PK': f'DOCUMENT#{tenant_id}',
                        'SK': _sk(package_id, doc_type, prior['version']),
                    },
                    UpdateExpression='SET #s = :superseded',
                    ExpressionAttributeNames={'#s': 'status'},
                    ExpressionAttributeValues={':superseded': 'superseded'},
                )
            except (ClientError, BotoCoreError) as e:
                logger.warning(
                    'document_store.create_document_from_s3: failed to supersede v%s: %s',
                    prior['version'], e,
                )

    return item
