"""
Document Provenance Metadata Tests

Verifies that every generated document includes a required
'## Document Metadata' section citing the template used, source,
version, and generation timestamp.

Run: pytest server/tests/test_document_provenance_metadata.py -v
"""

import os
import re
import sys
from datetime import datetime
from unittest.mock import MagicMock, patch

import pytest

# Ensure server/ is on sys.path so "app.*" resolves
_server_dir = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
if _server_dir not in sys.path:
    sys.path.insert(0, _server_dir)


# ── Constants ────────────────────────────────────────────────────────

ALL_DOC_TYPES = [
    "sow",
    "igce",
    "market_research",
    "justification",
    "acquisition_plan",
    "eval_criteria",
    "security_checklist",
    "section_508",
    "cor_certification",
    "contract_type_justification",
]

ENV_PATCH = {
    "REQUIRE_AUTH": "false",
    "DEV_MODE": "false",
    "USE_BEDROCK": "false",
    "COGNITO_USER_POOL_ID": "us-east-1_test",
    "COGNITO_CLIENT_ID": "test-client",
    "EAGLE_SESSIONS_TABLE": "eagle",
    "USE_PERSISTENT_SESSIONS": "false",
    "S3_BUCKET": "test-bucket",
}


# ── Helpers ──────────────────────────────────────────────────────────

def _mock_s3():
    """Return a MagicMock that behaves like a boto3 S3 client."""
    s3 = MagicMock()
    s3.put_object.return_value = {"ResponseMetadata": {"HTTPStatusCode": 200}}
    s3.list_objects_v2.return_value = {"Contents": []}
    return s3


# ── Fixtures ─────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def mock_s3_client():
    return _mock_s3()


# ══════════════════════════════════════════════════════════════════════
# T1 — Metadata section present in all doc types
# ══════════════════════════════════════════════════════════════════════

class TestProvenanceMetadata:
    """Verifies the Document Metadata section is required in all documents."""

    @pytest.mark.parametrize("doc_type", ALL_DOC_TYPES)
    def test_metadata_section_present_all_doc_types(self, doc_type, mock_s3_client):
        """Every doc type must include a Document Metadata section."""
        with patch.dict(os.environ, ENV_PATCH, clear=False):
            with patch("app.agentic_service._get_s3", return_value=mock_s3_client):
                from app.agentic_service import _exec_create_document
                result = _exec_create_document(
                    {"doc_type": doc_type, "title": f"Test {doc_type}"},
                    tenant_id="test-tenant",
                    session_id="ses-prov-001",
                )
        content = result["content"]
        assert "## Document Metadata" in content, (
            f"{doc_type}: missing '## Document Metadata' section"
        )
        assert "Generated by" in content, (
            f"{doc_type}: missing 'Generated by' row"
        )
        assert "Template" in content, (
            f"{doc_type}: missing 'Template' row"
        )

    def test_metadata_contains_template_info(self, mock_s3_client):
        """When template_id is provided, it appears in the metadata."""
        with patch.dict(os.environ, ENV_PATCH, clear=False):
            with patch("app.agentic_service._get_s3", return_value=mock_s3_client):
                from app.agentic_service import _exec_create_document
                result = _exec_create_document(
                    {
                        "doc_type": "sow",
                        "title": "SOW with Template",
                        "template_id": "essential-templates/sow-template-v2.docx",
                    },
                    tenant_id="test-tenant",
                    session_id="ses-prov-002",
                )
        content = result["content"]
        # The resolved template path may differ from the input template_id
        # (e.g. "sow-template-v2.docx" resolves to "statement-of-work-template-eagle-v2.docx")
        assert "essential-templates/" in content, (
            "template_id not cited in metadata"
        )
        assert "Template Source" in content

    def test_metadata_graceful_without_provenance(self, mock_s3_client):
        """Markdown fallback docs still get metadata with fallback values."""
        with patch.dict(os.environ, ENV_PATCH, clear=False):
            with patch("app.agentic_service._get_s3", return_value=mock_s3_client):
                from app.agentic_service import _exec_create_document
                result = _exec_create_document(
                    {"doc_type": "eval_criteria", "title": "Eval Criteria"},
                    tenant_id="test-tenant",
                    session_id="ses-prov-003",
                )
        content = result["content"]
        assert "## Document Metadata" in content
        assert "Built-in markdown generator" in content, (
            "fallback template label missing"
        )

    def test_old_footer_replaced(self, mock_s3_client):
        """The old bare EAGLE footer must not appear outside the metadata section."""
        with patch.dict(os.environ, ENV_PATCH, clear=False):
            with patch("app.agentic_service._get_s3", return_value=mock_s3_client):
                from app.agentic_service import _exec_create_document
                result = _exec_create_document(
                    {"doc_type": "sow", "title": "Footer Test"},
                    tenant_id="test-tenant",
                    session_id="ses-prov-004",
                )
        content = result["content"]
        # Split at the metadata heading
        parts = content.split("## Document Metadata")
        pre_metadata = parts[0]
        # The old footer should NOT appear before the metadata section
        assert "*This document was generated by EAGLE" not in pre_metadata, (
            "Old bare footer still present above metadata section"
        )

    def test_ai_content_gets_metadata(self, mock_s3_client):
        """AI-provided content also gets the metadata section appended."""
        ai_content = (
            "# My Custom SOW\n\nThis is AI-generated content.\n\n"
            "---\n*This document was generated by EAGLE \u2014 NCI Acquisition Assistant*"
        )
        with patch.dict(os.environ, ENV_PATCH, clear=False):
            with patch("app.agentic_service._get_s3", return_value=mock_s3_client):
                from app.agentic_service import _exec_create_document
                result = _exec_create_document(
                    {
                        "doc_type": "sow",
                        "title": "AI SOW",
                        "content": ai_content,
                    },
                    tenant_id="test-tenant",
                    session_id="ses-prov-005",
                )
        content = result["content"]
        assert "## Document Metadata" in content
        # Old footer should be replaced
        pre_metadata = content.split("## Document Metadata")[0]
        assert "*This document was generated by EAGLE" not in pre_metadata


# ══════════════════════════════════════════════════════════════════════
# T2 — Helper function unit tests
# ══════════════════════════════════════════════════════════════════════

class TestAppendProvenanceMetadataHelper:
    """Direct unit tests for _append_provenance_metadata()."""

    def test_double_injection_guard(self):
        """Content with existing metadata section is returned unchanged."""
        with patch.dict(os.environ, ENV_PATCH, clear=False):
            from app.agentic_service import _append_provenance_metadata
            content = "# Doc\n\n## Document Metadata\n\n| Field | Value |\n"
            result = _append_provenance_metadata(content, None, "test", "2026-03-25")
            assert result == content

    def test_metadata_renders_in_docx(self):
        """Metadata section markdown renders through markdown_to_docx without errors."""
        with patch.dict(os.environ, ENV_PATCH, clear=False):
            from app.agentic_service import _append_provenance_metadata
            from app.document_export import markdown_to_docx

            content = "# Test Document\n\nSome content here.\n"
            provenance = {
                "template_id": "sow-template-v2.docx",
                "template_source": "s3_template",
                "template_version": 1,
                "doc_type": "sow",
            }
            enriched = _append_provenance_metadata(
                content, provenance, "s3_template", "2026-03-25 14:30 UTC"
            )
            # Should not raise
            docx_bytes = markdown_to_docx(enriched, title="Test Document")
            assert len(docx_bytes) > 0

            # Verify the DOCX contains the metadata heading
            from io import BytesIO
            from docx import Document
            doc = Document(BytesIO(docx_bytes))
            headings = [p.text for p in doc.paragraphs if p.style.name.startswith("Heading")]
            assert any("Document Metadata" in h for h in headings), (
                f"'Document Metadata' heading not found in DOCX. Headings: {headings}"
            )
